security:
  oauth2:
    client:
      clientId: x  
      clientSecret: x
      accessTokenUri: https://login.elixir-czech.org/oidc/token
      userAuthorizationUri: https://login.elixir-czech.org/oidc/authorize
      tokenName: oauth_token
      scope: openid, bona_fide_status 
    resource:
      userInfoUri: https://login.elixir-czech.org/oidc/userinfo

